[package]
name = "atree_rust"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4"

[profile.dev.package.'*']
opt-level = 3

[profile.release]
lto = true
opt-level = 3